### ISSUE TITLE
Unable to run code

### ISSUE THREAD

**Issue by hari-sikchi** [Div99/XQL#1]
Hi authors!

I am having difficulty setting up the environment for this work. Do you have an environment.yml file that you can share?

Also there's some minor bugs at some places in code (floating m at the end of the line): https://github.com/Div99/XQL/blob/1eaaef581f002c3bfd38a628e19ab91477489067/offline/critic.py#L20

**Comment by Div-Infinity** [comment]
Thanks for pointing out the typo, just fixed! Will try to upload an environment.yml file too

**Comment by jhejna** [comment]
Hi! I've just uploaded the exact output of `pip freeze` I used to run some of the experiments to a file called `requirements_exact.txt`. You should be able to use this file to create the same env I have with python 3.8.13. We use the same environment as [IQL](https://github.com/ikostrikov/implicit_q_learning) for offline experiments.

I'm closing this thread for now, but feel free to re-open it if issues persist!

**Comment by jhejna** [comment]
Hi! I've just uploaded the exact output of `pip freeze` I used to run some of the experiments to a file called `requirements_exact.txt`. You should be able to use this file to create the same env I have with python 3.8.13. We use the same environment as [IQL](https://github.com/ikostrikov/implicit_q_learning) for offline experiments.

I'm closing this thread for now, but feel free to re-open it if issues persist!
